#!/bin/sh

if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
  echo 'usage: ik-update-release [<files>]'
  exit
fi

date=`date -u +'%Y-%m-%dT%H:%M:%S'`

if [ -n "$1" ]; then
  for arg in "$@"; do
    sed -i "s/^rel=.*/rel='$date'/" "$arg"
  done
else
  echo "$date"
fi
